-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agendamento (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_profissional uuid,
  tipo_recorrencia smallint,
  horario_agendamento time without time zone,
  data_agendamento date,
  observacao text,
  status smallint,
  dia_semana smallint,
  CONSTRAINT agendamento_pkey PRIMARY KEY (id),
  CONSTRAINT agendamento_id_profissional_fkey FOREIGN KEY (id_profissional) REFERENCES public.usuario(id)
);
CREATE TABLE public.agendamento_assistido (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_agendamento uuid NOT NULL,
  id_assistido uuid NOT NULL,
  status smallint,
  CONSTRAINT agendamento_assistido_pkey PRIMARY KEY (id),
  CONSTRAINT agendamento_assistido_id_agendamento_fkey FOREIGN KEY (id_agendamento) REFERENCES public.agendamento(id),
  CONSTRAINT agendamento_assistido_id_assistido_fkey FOREIGN KEY (id_assistido) REFERENCES public.assistido(id)
);
CREATE TABLE public.assistido (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  data_nascimento date,
  endereco character varying,
  observacao text,
  id_convenio uuid,
  data_cadastro date DEFAULT CURRENT_DATE,
  naturalidade character varying,
  tipo_deficiencia smallint,
  cid character varying,
  medicamentos_uso boolean DEFAULT false,
  medicamentos_quais text,
  nome_responsavel character varying,
  telefone_responsavel character varying,
  cpf character varying,
  bairro character varying,
  id_municipio uuid,
  cep character varying,
  nome_mae character varying,
  nome_pai character varying,
  descricao_demanda text,
  bpc boolean,
  bolsa_familia boolean,
  passe_livre_estadual boolean,
  passe_livre_municipal boolean,
  composicao_familiar text,
  plano_saude smallint,
  descricao_gestacao text,
  uso_medicacao_mae text,
  gestacao_semanas smallint,
  internacao_pos_nascimento boolean,
  medico_responsavel character varying,
  exames_realizados text,
  doencas_fisicas text,
  qualidade_sono text,
  cirurgias_realizadas text,
  doencas_neurologicas text,
  historico_familiar_doencas text,
  caracteristicas_marcantes text,
  boa_socializacao boolean,
  boa_adaptacao boolean,
  comportamento_agressivo boolean,
  controle_esfincteres boolean,
  apego_familiar character varying,
  atraso_alimentacao boolean,
  atraso_higiene boolean,
  atraso_vestuario boolean,
  atraso_locomocao boolean,
  atraso_comunicacao boolean,
  acompanhamento_especializado boolean,
  nome_escola text,
  ano_escola character varying,
  turno_escola smallint,
  pais_casados boolean,
  paternidade_registrada boolean,
  responsavel_busca character varying,
  consentimento_imagem boolean,
  status smallint,
  sexo smallint,
  nome_turma_apae character varying,
  turno_turma_apae smallint,
  dias_turma_apae character varying,
  CONSTRAINT assistido_pkey PRIMARY KEY (id),
  CONSTRAINT assistido_id_convenio_fkey FOREIGN KEY (id_convenio) REFERENCES public.convenio(id),
  CONSTRAINT assistido_id_municipio_fkey FOREIGN KEY (id_municipio) REFERENCES public.municipio(id)
);
CREATE TABLE public.atendimento (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_agendamento uuid NOT NULL,
  data_atendimento timestamp without time zone,
  presenca smallint,
  avaliacao text,
  observacao text,
  status smallint,
  id_assistido uuid,
  CONSTRAINT atendimento_pkey PRIMARY KEY (id),
  CONSTRAINT atendimento_id_agendamento_fkey FOREIGN KEY (id_agendamento) REFERENCES public.agendamento(id),
  CONSTRAINT atendimento_id_assistido_fkey FOREIGN KEY (id_assistido) REFERENCES public.assistido(id)
);
CREATE TABLE public.convenio (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  id_municipio uuid,
  nome character varying NOT NULL,
  observacao text,
  tipo_convenio_cas character varying,
  status character varying,
  CONSTRAINT convenio_pkey PRIMARY KEY (id),
  CONSTRAINT convenio_cas_id_municipio_fkey FOREIGN KEY (id_municipio) REFERENCES public.municipio(id)
);
CREATE TABLE public.municipio (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  cep_inicio character varying NOT NULL,
  cep_fim character varying NOT NULL,
  uf character NOT NULL DEFAULT 'RS'::bpchar,
  status boolean DEFAULT true,
  CONSTRAINT municipio_pkey PRIMARY KEY (id)
);
CREATE TABLE public.usuario (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  telefone character varying,
  senha character varying NOT NULL,
  perfil smallint NOT NULL,
  observacao text,
  updated_at timestamp with time zone,
  registro_profissional character varying,
  especialidade character varying,
  status smallint,
  CONSTRAINT usuario_pkey PRIMARY KEY (id)
);


