services:
  - type: web
    name: sistema-apae-api
    runtime: docker
    dockerfilePath: ./SistemaApae.Api/Dockerfile
    dockerContext: ./SistemaApae.Api
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /api/public/ping
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 8080
    autoDeploy: true
